### ISSUE TITLE
Portal upload: throwing error_ missing website.json file

### ISSUE THREAD

**Issue by ragavanrajan** [OOlashyn/portal-helper-vscode#1]
Hi @OOlashyn , 

    Thank you for the Powerapps portal helper extension. Indeed it is really useful. I started using it heavily. One of the issue I am facing while uploading the portal is the missing website.json error. Even though the CLI says portal upload is succeeded but it isn't. 

Screenshot for your reference. 

![image](https://user-images.githubusercontent.com/6369107/122144759-2aa1b380-cea8-11eb-94b2-c7d4eabd9daf.png)

Any help is appreciated.

**Comment by OOlashyn** [comment]
Hi @ragavanrajan,

This error usually occur if the folder you specified in the path is not the folder with the portal data. Can you confirm that TSSandboxPortal is the folder that was created by pac cli during download command and contains website.yml file? Also which version of pac you have? Also when did you download the portal? When portal cli was in preview it was working with json, but now it operates with yml files.

**Comment by ragavanrajan** [comment]
Hi @OOlashyn ,

Here is my power platform cli version

PS E:\MyDev\MyPowerApps\PowerApps Portal\TSSandboxPortal> 

Microsoft PowerApps CLI
Version: 1.6.7+g5031575

I can confirm that it contains web.yml file but the folder TSSAndboxPortal I have created manually. The CLI is not creating automatically. When I try to update the pac it simply fails. Screenshot below

![image](https://user-images.githubusercontent.com/6369107/122319218-6bff9500-cf74-11eb-84fc-92a43cb71afa.png)

**Comment by OOlashyn** [comment]
Sorry for the long reply.
I think the pac update is failing because you have Power Platform VS Code extension installed and it contains a version that cannot be updated via command line (as of now). When you download the portal it should create a folder for it (something like starter-portal etc) that contains all the file. Open that folder as a root folder of your workspace in VS Code and try to upload portal again.

**Comment by ragavanrajan** [comment]
Thanks again OOlashyn. Yes, I figured I should go inside the folder which is starter-portal and then it works like a charm. Thanks again.
